      ! Implementation of Continuum Species Transport (CST) for Nek5000
      !
      ! This module can be configured via userParam04 in your .par
      ! (parameter) file.
      !
      ! PARAMETER 04: Continuum Species Transport equation version.
      !   0 = Marschall (2012)
      !   1 = Li and Su (2025)
      ! Affects 2 terms, speciesSrc() called by userq and speciesDiff()
      ! called by uservp.
      
      real function speciesDiff(ix,iy,iz,el)
      ! Calculate the coefficient for the diffusion term in the CST
      ! transport equation.
      implicit none
      include 'SIZE'
      include 'TOTAL'
      include 'CASE'

      integer ix, iy, iz, el
      integer species_equation_version
      real psi

      psi = t(ix,iy,iz,el,ifld_cls-1)
      species_equation_version = int(uparam(iprm_cst_ver))
      if (species_equation_version .eq. 0) then
        ! Marschall et al (2012) version
        speciesDiff = ((1.0-psi)*diffratio + psi)/Pe
      else
        ! Li and Su (2025) version
        speciesDiff = (psi/(psi+(1.0-psi)*solubilityratio) +
     $      diffratio*(1.0-psi)/((1.0-psi)+psi/solubilityratio))/Pe
      endif

      endfunction

      real function speciesSrc(ix,iy,iz,el)
      ! Calculate the source terms in the CST transport equation.
      implicit none
      include 'SIZE'
      include 'TOTAL'
      include 'CASE'

      integer ix, iy, iz, el

      common /speciestransport/
     $                stmp(lx1,ly1,lz1,lelv),
     $                delta(lx1,ly1,lz1,lelv),
     $                spx(lx1,ly1,lz1,lelv),
     $                spy(lx1,ly1,lz1,lelv), 
     $                spz(lx1,ly1,lz1,lelv),
     $                spdiv(lx1,ly1,lz1,lelv)
      real stmp, delta, spx, spy, spz, spdiv
      
      real psi, term1, term2
      integer i, ntot, species_equation_version

      ntot = lx1*ly1*lz1*nelt

      ! If ix = iy = iz = el = 1 (e.g. only on the first GLL point
      ! on the first local element), do all the work.
      if(ix*iy*iz*el .eq. 1)then
        ! For each local GLL point on each local element:
        ! (This seems to be just shorthand for iterating over all 4
        ! dimensions in 1 loop (due to array ordering).)
        do i=1,ntot
          ! Scalar field value t(ix,iy,iz,el,ifield-1) for field
          ! number ifield.  So this is reading a length ntot array
          ! starting at ix=i, iy=1, iz=1, el=1 from CLS field.
          ! psi(:) = t(:, ifield=ifld_cls)
          psi = t(i,1,1,1,ifld_cls-1)
          ! Clip to [0, 1].
          psi = max(0.0,psi)
          psi = min(1.0,psi)
          ! Accumulation coefficient.
          species_equation_version = int(uparam(iprm_cst_ver))
          if (species_equation_version .eq. 0) then
            ! Marschall (2012) version
            term1 = 1.0 - diffratio
          else
            ! Li and Su (2025) version
            term1 = ((1.0 - diffratio)/solubilityratio)
     $               / ((psi/solubilityratio+(1.0-psi))**2)
          endif
          ! CST coefficient.
          term2 = (1.0 - diffratio/solubilityratio)
     $            / (psi/solubilityratio + (1.0-psi))
          stmp(i,1,1,1) = term1 - term2
        enddo
        ! Multiply by current c field.
        ! stmp(:) = stmp(:) * t(:, ifield=5)
        call col2(stmp, t(1,1,1,1,5),ntot)

        ! Read CLS field and calculate corrected (how so?) version.
        ! delta = 1/(4*epsilon) (cosh(clip(atanh(2*phi - 1))))^(-2)
        call deltals(t(1,1,1,1,ifld_cls-1),delta)
        ! Read normals into spx, spy, spz.
        call cls_normals(spx,spy,spz,ifld_tls)
        ! spx(:) = spx(:) * delta(:) * stmp(:)
        ! Delta seems to be some sort of correction factor for the
        ! interface normal vectors generated by cls_normals.
        call col4(spx,spx,delta,stmp,ntot)
        call col4(spy,spy,delta,stmp,ntot)
        call col4(spz,spz,delta,stmp,ntot)

        ! Divergence of the interface normal vector field sp =
        ! (spx, spy, spz)
        ! spdiv = div(sp)
        call opdiv(spdiv,spx,spy,spz)
        ! Multiply spdiv by QQ^T (scatter/gather operators) to convert
        ! from global to local coordinates.
        call dssum(spdiv,lx1,ly1,lz1)
        ! spdiv(:) = spdiv(:) * binvm1(:)
        ! binvm1 is the "inverse mass matrix for velocity mesh".
        call col2(spdiv,binvm1,ntot)
      endif

      ! For the rest of the elements/GLL points, just look up based on
      ! work already done.
      speciesSrc = spdiv(ix,iy,iz,el)/Pe
      endfunction
