      real function speciesSrc(ix,iy,iz,eg)
      implicit none
      include 'SIZE'
      include 'TOTAL'
      include 'SPECIES'

      integer ix,iy,iz,eg

      common /ls_usr/ ifld_cls,ifld_clsr,
     $                ifld_tls,ifld_tlsr 
      integer ifld_cls,ifld_clsr
      integer ifld_tls,ifld_tlsr

      common /speciestransport/
     $                stmp(lx1,ly1,lz1,lelv),
     $                delta(lx1,ly1,lz1,lelv),
     $                spx(lx1,ly1,lz1,lelv),
     $                spy(lx1,ly1,lz1,lelv), 
     $                spz(lx1,ly1,lz1,lelv) 
      real stmp, delta, spx, spy, spz
      real psi
      real term1, term2
      real He

      integer i,ntot

      He = 0.2802

      ntot = lx1*ly1*lz1*nelt 

      ! If ix = iy = iz = eg = 1 (e.g. only on the first GLL point
      ! on the first global element), do all the work.
      if(ix*iy*iz*eg .eq. 1)then
        ! For each local GLL point on each local element:
        ! (This seems to be just shorthand for iterating over all 4
        ! dimensions in 1 loop (due to array ordering).)
        do i=1,ntot
          ! Scalar field value t(ix,iy,iz,ie,ifield-1) for field
          ! number ifield.  So this is reading a length ntot array
          ! starting at ix=i, iy=1, iz=1, ie=1 from CLS field.
          ! psi(:) = t(:, ifield=ifld_cls)
          psi = t(i,1,1,1,ifld_cls-1)
          ! Clip to [0, 1].
          psi = max(0.0,psi)
          psi = min(1.0,psi)
          ! Accumulation coefficient.
          ! div(C*grad(D)) = div(term1*C*grad(alpha))
          term1 = diffl - diffg
          ! CST coefficient.
          term2 = (diffl - He*diffg)/(psi + He*(1.0-psi))
          stmp(i,1,1,1) = term1 - term2
        enddo
        ! Multiply by current c field.
        ! stmp(:) = stmp(:) * t(:, ifield=5)
        call col2(stmp, t(1,1,1,1,5),ntot)

        ! Read CLS field and calculate corrected (how so?) version.
        ! delta = 1/(4*epsilon) (cosh(clip(atanh(2*phi - 1))))^(-2)
        call deltals(t(1,1,1,1,ifld_cls-1),delta)
        ! Read normals into spx, spy, spz.
        call cls_normals(spx,spy,spz,ifld_tls)
        ! spx(:) = spx(:) * delta(:) * stmp(:)
        ! Delta seems to be some sort of correction factor for the
        ! interface normal vectors generated by cls_normals.
        call col4(spx,spx,delta,stmp,ntot)
        call col4(spy,spy,delta,stmp,ntot)
        call col4(spz,spz,delta,stmp,ntot)

        ! Divergence of the interface normal vector field sp =
        ! (spx, spy, spz)
        ! spdiv = div(sp)
        call opdiv(spdiv,spx,spy,spz)
        ! Multiply spdiv by QQ^T (scatter/gather operators) to convert
        ! from local to global coordinates.
        ! something like that?
        call dssum(spdiv,lx1,ly1,lz1)
        ! spdiv(:) = spdiv(:) * binvm1(:)
        ! binvm1 is the "inverse mass matrix for velocity mesh".
        call col2(spdiv,binvm1,ntot)
      endif

      ! For the rest of the elements/GLL points, just look up based on
      ! work already done.
      speciesSrc = spdiv(ix,iy,iz,eg)